### ISSUE TITLE
uint64 overflowing float64

### ISSUE THREAD

**Issue by RichiH** [richardelling/zpool_prometheus#1]
For anything that's a counter, just do `mod 2^52` and Prometheus will handle the counter reset gracefully within `rate()` etc.

**Comment by richardelling** [comment]
Thanks for the info, a similar masking was implemented in 692ea0b947c93fded2c7cf430b3351b19dffedc5

Today, we're in pretty good shape wrt reporting counters. The reporting of state is much more tricky because the values of state are enums that change over time, so we're really like to use strings rather than numbers for their representation.
